<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>SciterMidi.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <UseWindowsForms>true</UseWindowsForms>
    
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);SCITER_JS_NEW</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);SCITER_JS_NEW</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Include="runtimes\linux-arm64\native\libsciter.so" Pack="true" PackagePath="runtimes/linux-arm64/native/"></None>
    <None Include="runtimes\linux-x64\native\libsciter.so" Pack="true" PackagePath="runtimes/linux-x64/native/"></None>
    <None Include="runtimes\win-x64\native\sciter.dll" Pack="true" PackagePath="runtimes/win-x64/native/"></None>
    <None Include="runtimes\win-x86\native\sciter.dll" Pack="true" PackagePath="runtimes/win-x86/native/"></None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.213">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>